# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a670250686800f0bb4e694bf3c331b2466112379ddd3c7f78ff6d3741ad0677306d313a271cd21b82b8045f60d29442734cb36df64e4d211fa506d5d3c2fcfd4

test:
  secret_key_base: 37d95c4976a6efb674b33c61df0cd5b2aa13738fbeef8722a6bce02bdebe2ef58c049cfdbb8686ffd53a8a8409e245c4f444b0923231d2c68aeb78c896fe2ba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
